-- Friendza / Frienza PostgreSQL schema initialization
-- Run this script inside your target database, e.g.:
--   psql -U <user> -d <db_name> -f init.sql

BEGIN;

-- Optional: ensure consistent timestamps (comment out if you prefer server defaults)
-- SET TIME ZONE 'UTC';

-- =========================================
-- USERS
-- =========================================
CREATE TABLE IF NOT EXISTS users (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username          VARCHAR NOT NULL UNIQUE,
  email             VARCHAR NOT NULL UNIQUE,
  password_hash     TEXT NOT NULL,
  full_name         VARCHAR,
  bio               TEXT,
  avatar_url        TEXT,
  created_at        TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  is_private        BOOLEAN DEFAULT false
);

CREATE INDEX IF NOT EXISTS idx_users_created_at ON users (created_at);

-- =========================================
-- POSTS
-- =========================================
CREATE TABLE IF NOT EXISTS posts (
  id                       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id                  INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  caption                  TEXT,
  created_at               TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  location                 VARCHAR,
  media_type               VARCHAR DEFAULT 'image',
  media_url                TEXT NOT NULL,
  media_duration_seconds   INTEGER,
  CONSTRAINT chk_posts_media_type CHECK (media_type IN ('image', 'video'))
);

CREATE INDEX IF NOT EXISTS idx_posts_user_id_created_at ON posts (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_posts_created_at ON posts (created_at DESC);

-- =========================================
-- STORIES
-- =========================================
CREATE TABLE IF NOT EXISTS stories (
  id                       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id                  INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  caption                  TEXT,
  created_at               TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  expires_at               TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (now() + interval '24 hours'),
  media_type               VARCHAR DEFAULT 'image',
  media_url                TEXT NOT NULL,
  media_duration_seconds   INTEGER,
  CONSTRAINT chk_stories_media_type CHECK (media_type IN ('image', 'video'))
);

CREATE INDEX IF NOT EXISTS idx_stories_user_id_expires_at ON stories (user_id, expires_at DESC);
CREATE INDEX IF NOT EXISTS idx_stories_expires_at ON stories (expires_at);

-- =========================================
-- FOLLOWS
-- =========================================
CREATE TABLE IF NOT EXISTS follows (
  follower_id   INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  following_id  INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at    TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  PRIMARY KEY (follower_id, following_id),
  CONSTRAINT chk_no_self_follow CHECK (follower_id <> following_id)
);

CREATE INDEX IF NOT EXISTS idx_follows_following_id ON follows (following_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_follows_follower_id ON follows (follower_id, created_at DESC);

-- =========================================
-- LIKES
-- =========================================
CREATE TABLE IF NOT EXISTS likes (
  user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  post_id     INTEGER NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  created_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  PRIMARY KEY (user_id, post_id)
);

CREATE INDEX IF NOT EXISTS idx_likes_post_id ON likes (post_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_likes_user_id ON likes (user_id, created_at DESC);

-- =========================================
-- SAVED POSTS
-- =========================================
CREATE TABLE IF NOT EXISTS saved_posts (
  user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  post_id     INTEGER NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  created_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  PRIMARY KEY (user_id, post_id)
);

CREATE INDEX IF NOT EXISTS idx_saved_posts_user_id ON saved_posts (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_saved_posts_post_id ON saved_posts (post_id, created_at DESC);

-- =========================================
-- COMMENTS
-- =========================================
CREATE TABLE IF NOT EXISTS comments (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  post_id     INTEGER NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  text        TEXT NOT NULL,
  created_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_comments_post_id_created_at ON comments (post_id, created_at ASC);
CREATE INDEX IF NOT EXISTS idx_comments_user_id_created_at ON comments (user_id, created_at DESC);

-- =========================================
-- Convenience view
-- =========================================
CREATE OR REPLACE VIEW active_stories AS
SELECT *
FROM stories
WHERE expires_at > now()
ORDER BY created_at DESC;

COMMIT;

